# action.yml
name: auto-update-changelog
description: Auto update your CHANGELOG on every push with previous commits
author: Md. Musfiqur Rahaman

branding:
    icon: "refresh-cw"
    color: "white"

inputs:
    # who-to-greet: # id of input
    #     description: "Who to greet"
    #     required: true
    #     default: "World"

    email: # Name of the User
        description: "Email of the User"
        required: true
        default: "Octocat@github.com"

    name: # Name of the User
        description: "Name of the User"
        required: true
        default: "Octocat"

# outputs:
#     time: # id of output
#         description: "The time we greeted you"

runs:
    using: "docker"
    image: "Dockerfile"
    args:
        # - ${{ inputs.who-to-greet }}
        - ${{ inputs.email }}
        - ${{ inputs.name }}
