name: auto-update-changelog
description: This Action will update your CHANGELOG file on every push with previous commits and trigger by following a particular commit message pattern
author: Md. Musfiqur Rahaman
branding:
  icon: 'refresh-cw'
  color: 'white'
